import { useEffect, useMemo, useState } from "react";
import { motion } from "framer-motion";
import { Area, AreaChart, ResponsiveContainer, Tooltip, XAxis } from "recharts";
import { api } from "./api";
import type { AnalysisStatus, Detection, Health, RiskLevel, Scene } from "./types";
import { GlassCard } from "./components/GlassCard";
import { MapView } from "./components/MapView";
import { StatusPill } from "./components/StatusPill";

type Language = "ru" | "kk";
type View = "dashboard" | "analysis" | "detections" | "detection" | "reports" | "about";

const DEFAULT_BBOX = [51.2, 42.25, 52.5, 43.2];
const monitoredAreas = [
  { id: "aktau", point: [43.36, 51.18] as [number, number] },
  { id: "kashagan", point: [46.25, 51.55] as [number, number] },
  { id: "atyrau", point: [46.82, 51.72] as [number, number] },
  { id: "central", point: [42.7, 51.7] as [number, number] },
];

const text = {
  ru: {
    nav: ["Обзор", "Анализ зоны", "Обнаружения", "Отчёты", "О проекте"],
    titles: ["Экологический обзор", "Анализ выбранной зоны", "Журнал обнаружений", "Карточка обнаружения", "Экологические отчёты", "О платформе"],
    workspace: "Рабочее пространство", system: "Состояние системы", operational: "Система работает", connecting: "Подключение…", configurationRequired: "Требуется настройка", setupMode: "НАСТРОЙКА",
    mission: "Спутниковый мониторинг Каспийского моря", live: "Спутниковые данные", latest: "последний доступный снимок",
    newAnalysis: "Новый анализ", readiness: "Готовность live-режима", readinessText: "Для реального анализа подключите Copernicus и проверенные веса модели.",
    copernicus: "Copernicus", model: "AI-модель", ready: "готово", needed: "не подключено",
    monitored: "Зоны наблюдения", scenes: "Доступные сцены", signals: "Сигналы", mode: "Режим данных",
    quickAreas: "Быстрый выбор зоны", chooseZone: "Выберите участок для мониторинга", areaNames: ["Побережье Актау", "Кашаган", "Шельф Атырау", "Центральный Каспий"],
    layers: "Слои карты", satelliteLayer: "Снимок Sentinel-1", detectionLayer: "AI-обнаружения", opacity: "Прозрачность",
    realAcquisition: "Последняя доступная сцена", high: "Высокий", medium: "Средний", low: "Низкий",
    selectHint: "Нажмите на карту, чтобы разместить область анализа", selectedAt: "Область выбрана", selectPrompt: "Сначала выберите точку на карте",
    currentData: "Текущий источник", noScene: "Сцена ещё не загружена", getScene: "Получить последний снимок", searching: "Поиск…", runAi: "Запустить AI-анализ", analyzing: "Анализ",
    latestScene: "Последняя сцена", satelliteAcquisition: "Спутниковая съёмка", acquired: "Дата съёмки", orbit: "Направление орбиты", resolution: "Разрешение", sceneId: "ID сцены",
    latestDetection: "Последнее обнаружение", aiScreening: "AI-СКРИНИНГ", estimatedArea: "Расчётная площадь", meanConfidence: "Средняя уверенность", noAnalyses: "Анализов пока нет", noAnalysesText: "Выберите зону и запустите проверку снимка.", analyzeArea: "Перейти к анализу", details: "Открыть карточку",
    humanRequired: "Требуется проверка специалистом", humanText: "Тёмные участки SAR могут иметь разные причины. Результат AI помогает расставить приоритеты, но не подтверждает загрязнение.", report: "Сформировать экологический отчёт",
    trend: "Динамика сигнала", screeningConfidence: "Уверенность скрининга", actualSequence: "только реальные результаты", now: "Сейчас",
    workflow: "ПОРЯДОК РАБОТЫ", workflowTitle: "Проверка нефтеподобных аномалий", workflowIntro: "Выберите участок и обработайте последний доступный снимок Sentinel-1.",
    defineArea: "Определите зону", mapReady: "Область на карте готова", choosePoint: "Выберите точку", selectArea: "Выбрать на карте", clickMap: "Нажмите на карту",
    findLatest: "Найдите свежую сцену", daysBack: "Поиск за последние 14 дней", findScene: "Найти сцену", runScreening: "Запустите скрининг", detectionReady: "Результат готов", openModel: "Open-source U-Net и оценка риска", runAnalysis: "Запустить",
    stages: ["поиск данных", "загрузка сцены", "подготовка SAR", "работа модели", "создание полигонов", "оценка риска"],
    register: "ЖУРНАЛ СОБЫТИЙ", screened: "Обнаруженные сигналы", anomaly: "Потенциальная нефтеподобная аномалия", noDetections: "Обнаружений пока нет", noDetectionsText: "Запустите анализ — результат появится здесь и на карте.",
    reportCenter: "ЦЕНТР ОТЧЁТОВ", reportTitle: "Экологические отчёты", reportIntro: "PDF содержит источник данных, версию модели, геометрию, уверенность, ограничения и требование полевой проверки.", reportName: "Отчёт", downloadAgain: "Скачать снова", generatePdf: "Создать PDF", noReport: "Нет данных для отчёта", noReportText: "Сначала завершите анализ выбранной зоны.",
    back: "Назад к обнаружениям", incident: "СОБЫТИЕ", potential: "Потенциальная нефтеподобная аномалия", warning: "Потенциальная нефтеподобная аномалия, требующая проверки на месте.", preview: "Реальный снимок Sentinel-1", mask: "Маска open-source U-Net", result: "РЕЗУЛЬТАТ СКРИНИНГА", metrics: "Показатели обнаружения", maxConfidence: "Максимальная уверенность", coordinates: "Координаты", modelVersion: "Версия модели", verification: "Проверка", fieldCheck: "Нужна полевая проверка",
    responsible: "ЦЕНТР ПРОВЕРКИ", nextAction: "Решение оператора", nextText: "Перед официальным выводом специалист должен сравнить сигнал с погодой, ветром и движением судов, затем организовать полевую проверку.", source: "Источник", confirm: "Подтвердить сигнал", falsePositive: "Ложное срабатывание", escalate: "Эскалировать",
    aboutEyebrow: "ЭКОЛОГИЧЕСКАЯ АНАЛИТИКА / КАСПИЙСКОЕ МОРЕ", aboutHero: "От спутникового снимка — к понятному плану полевой проверки.", aboutText: "Caspian Guardian AI анализирует последние доступные SAR-снимки Sentinel-1 и выделяет потенциальные нефтеподобные аномалии. Платформа помогает решать, куда направить внимание, но не заменяет экологов и официальную экспертизу.", explore: "Посмотреть процесс анализа",
    observe: "НАБЛЮДЕНИЕ", observeTitle: "Готово к Copernicus", observeText: "Защищённый OAuth2, поиск Sentinel-1 GRD и получение каналов VV/VH.", screen: "СКРИНИНГ", screenTitle: "Открытая модель", screenText: "Заменяемая U-Net с прозрачной уверенностью и версией модели.", verify: "ПРОВЕРКА", verifyTitle: "Ответственное решение", verifyText: "GeoJSON, приоритет риска и PDF-пакет для полевой команды.", scalability: "РАЗВИТИЕ", beyond: "Дальше — больше экологических задач", beyondText: "Архитектура допускает модули качества воды, морского мусора, незаконного рыболовства и загрязнения береговой линии.",
    risk: { LOW: "Низкий", MEDIUM: "Средний", HIGH: "Высокий" } as Record<RiskLevel, string>,
    errors: { load: "Не удалось подключиться к API", scene: "Не удалось найти сцену", analysis: "Не удалось запустить анализ", status: "Не удалось получить статус", report: "Не удалось создать отчёт" },
  },
  kk: {
    nav: ["Шолу", "Аймақты талдау", "Анықтаулар", "Есептер", "Жоба туралы"],
    titles: ["Экологиялық шолу", "Таңдалған аймақты талдау", "Анықтаулар журналы", "Анықтау картасы", "Экологиялық есептер", "Платформа туралы"],
    workspace: "Жұмыс кеңістігі", system: "Жүйе күйі", operational: "Жүйе жұмыс істеп тұр", connecting: "Қосылу…", configurationRequired: "Баптау қажет", setupMode: "БАПТАУ",
    mission: "Каспий теңізінің спутниктік мониторингі", live: "Спутниктік деректер", latest: "соңғы қолжетімді түсірілім",
    newAnalysis: "Жаңа талдау", readiness: "Live режимінің дайындығы", readinessText: "Нақты талдау үшін Copernicus пен тексерілген модель салмақтарын қосыңыз.",
    copernicus: "Copernicus", model: "AI-модель", ready: "дайын", needed: "қосылмаған",
    monitored: "Бақылау аймақтары", scenes: "Қолжетімді көріністер", signals: "Сигналдар", mode: "Деректер режимі",
    quickAreas: "Аймақты жылдам таңдау", chooseZone: "Мониторинг аймағын таңдаңыз", areaNames: ["Ақтау жағалауы", "Қашаған", "Атырау қайраңы", "Орталық Каспий"],
    layers: "Карта қабаттары", satelliteLayer: "Sentinel-1 суреті", detectionLayer: "AI анықтаулары", opacity: "Мөлдірлік",
    realAcquisition: "Соңғы қолжетімді көрініс", high: "Жоғары", medium: "Орташа", low: "Төмен",
    selectHint: "Талдау аймағын орналастыру үшін картаны басыңыз", selectedAt: "Аймақ таңдалды", selectPrompt: "Алдымен картадан нүкте таңдаңыз",
    currentData: "Ағымдағы дереккөз", noScene: "Көрініс әлі жүктелмеді", getScene: "Соңғы суретті алу", searching: "Іздеу…", runAi: "AI-талдауды іске қосу", analyzing: "Талдау",
    latestScene: "Соңғы көрініс", satelliteAcquisition: "Спутниктік түсірілім", acquired: "Түсірілім күні", orbit: "Орбита бағыты", resolution: "Ажыратымдылық", sceneId: "Көрініс ID",
    latestDetection: "Соңғы анықтау", aiScreening: "AI-СКРИНИНГ", estimatedArea: "Есептік аудан", meanConfidence: "Орташа сенімділік", noAnalyses: "Талдау әлі жоқ", noAnalysesText: "Аймақты таңдап, суретті тексеруді бастаңыз.", analyzeArea: "Талдауға өту", details: "Картаны ашу",
    humanRequired: "Маманның тексеруі қажет", humanText: "SAR-дегі қараңғы аймақтардың себептері әртүрлі болуы мүмкін. AI нәтижесі басымдықты анықтайды, бірақ ластануды растамайды.", report: "Экологиялық есеп құру",
    trend: "Сигнал динамикасы", screeningConfidence: "Скрининг сенімділігі", actualSequence: "тек нақты нәтижелер", now: "Қазір",
    workflow: "ЖҰМЫС ТӘРТІБІ", workflowTitle: "Мұнайға ұқсас ауытқуларды тексеру", workflowIntro: "Аймақты таңдап, соңғы қолжетімді Sentinel-1 суретін өңдеңіз.",
    defineArea: "Аймақты белгілеңіз", mapReady: "Картадағы аймақ дайын", choosePoint: "Нүктені таңдаңыз", selectArea: "Картадан таңдау", clickMap: "Картаны басыңыз",
    findLatest: "Жаңа көріністі табыңыз", daysBack: "Соңғы 14 күн бойынша іздеу", findScene: "Көріністі табу", runScreening: "Скринингті іске қосыңыз", detectionReady: "Нәтиже дайын", openModel: "Open-source U-Net және қауіп бағасы", runAnalysis: "Іске қосу",
    stages: ["деректерді іздеу", "көріністі жүктеу", "SAR дайындау", "модель жұмысы", "полигондар құру", "қауіпті бағалау"],
    register: "ОҚИҒАЛАР ЖУРНАЛЫ", screened: "Анықталған сигналдар", anomaly: "Мұнайға ұқсас ықтимал ауытқу", noDetections: "Анықтаулар әлі жоқ", noDetectionsText: "Талдауды бастаңыз — нәтиже осында және картада пайда болады.",
    reportCenter: "ЕСЕПТЕР ОРТАЛЫҒЫ", reportTitle: "Экологиялық есептер", reportIntro: "PDF дереккөзді, модель нұсқасын, геометрияны, сенімділікті, шектеулерді және далалық тексеру талабын қамтиды.", reportName: "Есеп", downloadAgain: "Қайта жүктеу", generatePdf: "PDF құру", noReport: "Есепке дерек жоқ", noReportText: "Алдымен таңдалған аймақтың талдауын аяқтаңыз.",
    back: "Анықтауларға оралу", incident: "ОҚИҒА", potential: "Мұнайға ұқсас ықтимал ауытқу", warning: "Далалық тексеруді қажет ететін мұнайға ұқсас ықтимал ауытқу.", preview: "Нақты Sentinel-1 суреті", mask: "Open-source U-Net маскасы", result: "СКРИНИНГ НӘТИЖЕСІ", metrics: "Анықтау көрсеткіштері", maxConfidence: "Ең жоғары сенімділік", coordinates: "Координаттар", modelVersion: "Модель нұсқасы", verification: "Тексеру", fieldCheck: "Далалық тексеру қажет",
    responsible: "ТЕКСЕРУ ОРТАЛЫҒЫ", nextAction: "Оператор шешімі", nextText: "Ресми қорытындыға дейін маман сигналды ауа райы, жел және кеме қозғалысымен салыстырып, далалық тексеру ұйымдастыруы керек.", source: "Дереккөз", confirm: "Сигналды растау", falsePositive: "Жалған іске қосылу", escalate: "Эскалациялау",
    aboutEyebrow: "ЭКОЛОГИЯЛЫҚ ТАЛДАУ / КАСПИЙ ТЕҢІЗІ", aboutHero: "Спутниктік суреттен — түсінікті далалық тексеру жоспарына.", aboutText: "Caspian Guardian AI соңғы қолжетімді Sentinel-1 SAR суреттерін талдап, мұнайға ұқсас ықтимал ауытқуларды көрсетеді. Платформа назар аударатын орынды анықтауға көмектеседі, бірақ экологтар мен ресми сараптаманы алмастырмайды.", explore: "Талдау үдерісін көру",
    observe: "БАҚЫЛАУ", observeTitle: "Copernicus-ке дайын", observeText: "Қауіпсіз OAuth2, Sentinel-1 GRD іздеуі және VV/VH арналарын алу.", screen: "СКРИНИНГ", screenTitle: "Ашық модель", screenText: "Сенімділігі мен нұсқасы көрсетілген ауыстырмалы U-Net.", verify: "ТЕКСЕРУ", verifyTitle: "Жауапты шешім", verifyText: "GeoJSON, қауіп басымдығы және далалық топқа арналған PDF-пакет.", scalability: "ДАМУ", beyond: "Келесі экологиялық міндеттер", beyondText: "Архитектура су сапасы, теңіз қоқысы, заңсыз балық аулау және жағалау ластануы модульдерін қолдайды.",
    risk: { LOW: "Төмен", MEDIUM: "Орташа", HIGH: "Жоғары" } as Record<RiskLevel, string>,
    errors: { load: "API-ға қосылу мүмкін болмады", scene: "Көрініс табылмады", analysis: "Талдау іске қосылмады", status: "Күйді алу мүмкін болмады", report: "Есеп құру мүмкін болмады" },
  },
};

type Copy = typeof text.ru;

function formatDate(value: string | undefined, _language: Language) {
  if (!value) return "—";
  const date = new Date(value);
  const pad = (part: number) => String(part).padStart(2, "0");
  return `${pad(date.getUTCDate())}.${pad(date.getUTCMonth() + 1)}.${date.getUTCFullYear()}, ${pad(date.getUTCHours())}:${pad(date.getUTCMinutes())} UTC`;
}

export default function App() {
  const [language, setLanguageState] = useState<Language>(() => localStorage.getItem("guardian-language") === "kk" ? "kk" : "ru");
  const [view, setView] = useState<View>("dashboard");
  const [scene, setScene] = useState<Scene | null>(null);
  const [health, setHealth] = useState<Health | null>(null);
  const [detections, setDetections] = useState<Detection[]>([]);
  const [selectedDetection, setSelectedDetection] = useState<Detection | null>(null);
  const [selectedPoint, setSelectedPoint] = useState<[number, number] | null>(null);
  const [drawing, setDrawing] = useState(false);
  const [job, setJob] = useState<AnalysisStatus | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [showSatellite, setShowSatellite] = useState(true);
  const [showDetections, setShowDetections] = useState(true);
  const [layerOpacity, setLayerOpacity] = useState(68);
  const [generatedReports, setGeneratedReports] = useState<Record<string, string>>({});
  const t = text[language];
  const latest = detections.at(-1) ?? null;
  const activeDetection = selectedDetection ?? latest;
  const running = job?.status === "running" || job?.status === "queued";
  const selectedBbox = useMemo(() => selectedPoint ? [selectedPoint[1] - .34, selectedPoint[0] - .16, selectedPoint[1] + .34, selectedPoint[0] + .16] : DEFAULT_BBOX, [selectedPoint]);
  const views: View[] = ["dashboard", "analysis", "detections", "detection", "reports", "about"];
  const navViews: View[] = ["dashboard", "analysis", "detections", "reports", "about"];
  const icons = ["⌂", "⌁", "◉", "▤", "○"];

  useEffect(() => { void loadData(); }, []);

  function setLanguage(next: Language) { setLanguageState(next); localStorage.setItem("guardian-language", next); }
  async function loadData() { try { const h = await api.health(); setHealth(h); if (!h.live_ready) return; const [s, d] = await Promise.allSettled([api.latestScene(), api.detections()]); if (s.status === "fulfilled") setScene(s.value); if (d.status === "fulfilled") setDetections(d.value); } catch { setError(t.errors.load); } }
  async function findScene() { setError(null); setLoading(true); try { setScene(await api.searchScene(selectedBbox)); setShowSatellite(true); } catch { setError(t.errors.scene); } finally { setLoading(false); } }
  async function runAnalysis() { setError(null); setLoading(true); try { const queued = await api.startAnalysis(selectedBbox); setJob({ job_id: queued.job_id, status: queued.status, progress: 0, stage: "queued" }); pollJob(queued.job_id); } catch { setError(t.errors.analysis); } finally { setLoading(false); } }
  function pollJob(jobId: string) { const timer = window.setInterval(async () => { try { const next = await api.analysisStatus(jobId); setJob(next); if (next.status === "review" && next.detection_id) { window.clearInterval(timer); const detection = await api.detection(next.detection_id); setDetections((items) => [...items.filter((item) => item.id !== detection.id), detection]); setSelectedDetection(detection); setShowDetections(true); setView("detection"); } if (next.status === "failed") window.clearInterval(timer); } catch { window.clearInterval(timer); setError(t.errors.status); } }, 1500); }
  async function reviewDetection(action: "CONFIRM" | "FALSE_POSITIVE" | "ESCALATE") { if (!activeDetection) return; try { await api.review(activeDetection.id, action); const updated = await api.detection(activeDetection.id); setSelectedDetection(updated); setDetections((items) => items.map((item) => item.id === updated.id ? updated : item)); } catch { setError(t.errors.status); } }
  async function generateReport(detection = activeDetection) { if (!detection) return; try { const report = await api.createReport(detection.id, language); setGeneratedReports((items) => ({ ...items, [detection.id]: report.download_url })); window.open(`${api.apiUrl.replace("/api", "")}${report.download_url}`, "_blank"); } catch { setError(t.errors.report); } }
  function openDetection(detection: Detection) { setSelectedDetection(detection); setView("detection"); }

  return <div className="app-shell">
    <aside className="sidebar">
      <div className="brand"><div className="brand-mark"><span /></div><div><strong>CASPIAN GUARDIAN</strong><small>ENVIRONMENTAL AI</small></div></div>
      <div className="sidebar-label">{t.workspace}</div>
      <nav>{navViews.map((item, index) => <button key={item} className={view === item || (item === "detections" && view === "detection") ? "nav-item active" : "nav-item"} onClick={() => setView(item)}><span>{icons[index]}</span>{t.nav[index]}{item === "detections" && detections.length ? <em>{detections.length}</em> : null}</button>)}</nav>
      <div className="sidebar-spacer" />
      <div className="system-chip"><span className={health?.status === "ok" ? "pulse" : "pulse offline"} /><div><small>{t.system}</small><strong>{health ? (health.status === "ok" ? t.operational : t.configurationRequired) : t.connecting}</strong></div></div>
      <p className="sidebar-foot">{t.humanText}</p>
    </aside>

    <main className="main-content">
      <header className="topbar"><div><div className="eyebrow">{t.mission}</div><h1>{t.titles[views.indexOf(view)]}</h1></div><div className="top-actions"><div className="language-switch" aria-label="Тіл / Язык"><button className={language === "ru" ? "active" : ""} onClick={() => setLanguage("ru")}>RU</button><button className={language === "kk" ? "active" : ""} onClick={() => setLanguage("kk")}>ҚАЗ</button></div><div className={`data-mode ${health?.live_ready ? "real" : "setup"}`}><span className="mode-dot" /><div>{t.live}<small>{health?.live_ready ? t.latest : t.needed}</small></div></div><button className="button button-primary" onClick={() => setView("analysis")} disabled={!health?.live_ready}>＋ {t.newAnalysis}</button></div></header>
      {error ? <div className="error-banner">{error}<button onClick={() => setError(null)} aria-label="Закрыть">×</button></div> : null}
      <section className={`readiness-banner ${health?.live_ready ? "live" : ""}`}><div><span>{t.readiness}</span><strong>{health?.live_ready ? t.latest : t.readinessText}</strong></div><div className="readiness-checks"><i className={health?.credentials_configured ? "ready" : ""}>{t.copernicus}: {health?.credentials_configured ? t.ready : t.needed}</i><i className={health?.model_configured ? "ready" : ""}>{t.model}: {health?.model_configured ? t.ready : t.needed}</i></div></section>

      {view === "about" ? <AboutPage t={t} onAnalyze={() => setView("analysis")} /> : view === "detection" && activeDetection ? <DetectionDetailsPage detection={activeDetection} t={t} language={language} onBack={() => setView("detections")} onReport={() => void generateReport(activeDetection)} onReview={reviewDetection} /> : <>
        <section className="kpi-grid"><Kpi label={t.monitored} value="—" note={t.chooseZone} /><Kpi label={t.scenes} value={scene ? "1" : "0"} note={scene ? formatDate(scene.acquisition_time, language) : t.noScene} /><Kpi label={t.signals} value={String(detections.length)} note={detections.length ? t.latestDetection : t.noAnalyses} /><Kpi label={t.mode} value={health?.live_ready ? "LIVE" : t.setupMode} note={health?.live_ready ? t.latest : t.needed} tone={health?.live_ready ? "good" : "attention"} /></section>
        <div className="content-grid"><div className="map-column">
          <div className="area-presets"><div><span className="eyebrow">{t.quickAreas}</span><strong>{t.chooseZone}</strong></div><div>{monitoredAreas.map((area, index) => <button key={area.id} className={selectedPoint?.[0] === area.point[0] && selectedPoint?.[1] === area.point[1] ? "active" : ""} onClick={() => { setSelectedPoint(area.point); setView("analysis"); }}>{t.areaNames[index]}</button>)}</div></div>
          <div className="map-wrap"><MapView detections={detections} scene={scene} selectedPoint={selectedPoint} drawing={drawing} showSatellite={showSatellite} showDetections={showDetections} layerOpacity={layerOpacity} onSelect={(point) => { setSelectedPoint(point); setDrawing(false); }} />
            <div className="map-layers-panel"><div className="eyebrow">{t.layers}</div><label><input type="checkbox" checked={showSatellite} onChange={(e) => setShowSatellite(e.target.checked)} /> {t.satelliteLayer}</label><label><input type="checkbox" checked={showDetections} onChange={(e) => setShowDetections(e.target.checked)} /> {t.detectionLayer}</label><label className="opacity-control"><span>{t.opacity}</span><strong>{layerOpacity}%</strong><input aria-label={t.opacity} type="range" min="10" max="100" value={layerOpacity} onChange={(e) => setLayerOpacity(Number(e.target.value))} /></label></div>
            <div className="map-meta"><span className="live-indicator" />{t.realAcquisition}<b>{formatDate(scene?.acquisition_time, language)}</b></div><div className="map-legend"><span><i className="legend-swatch swatch-red" />{t.high}</span><span><i className="legend-swatch swatch-yellow" />{t.medium}</span><span><i className="legend-swatch swatch-green" />{t.low}</span></div>
            {view === "analysis" ? <div className="map-select-hint">{drawing ? t.selectHint : selectedPoint ? `${t.selectedAt}: ${selectedPoint[0].toFixed(3)}°N, ${selectedPoint[1].toFixed(3)}°E` : t.selectPrompt}</div> : null}</div>
          <div className="map-actions-strip"><div><span className="eyebrow">{t.currentData}</span><strong>{scene ? `${scene.satellite} • VV/VH` : t.noScene}</strong></div><div><button className="button button-secondary" onClick={() => void findScene()} disabled={loading}>{loading ? t.searching : t.getScene}</button><button className="button button-primary" onClick={() => void runAnalysis()} disabled={Boolean(running)}>{running ? `${t.analyzing}: ${job?.progress ?? 0}%` : t.runAi}</button></div></div>
          {view === "analysis" ? <AnalysisPanel t={t} language={language} scene={scene} loading={loading} running={Boolean(running)} job={job} drawing={drawing} selectedPoint={selectedPoint} onDraw={() => setDrawing(true)} onFind={findScene} onRun={runAnalysis} /> : view === "detections" ? <DetectionsPanel t={t} language={language} detections={detections} onOpen={openDetection} /> : view === "reports" ? <ReportsPanel t={t} language={language} detections={detections} generatedReports={generatedReports} onGenerate={(d) => void generateReport(d)} /> : <TrendCard t={t} detections={detections} />}
        </div><aside className="insight-column"><SceneCard t={t} language={language} scene={scene} /><DetectionCard t={t} detection={activeDetection} onAnalyze={() => setView("analysis")} onOpen={() => activeDetection && openDetection(activeDetection)} /><GlassCard className="verification-card"><div className="verification-icon">✓</div><div><strong>{t.humanRequired}</strong><p>{t.humanText}</p></div></GlassCard>{activeDetection ? <button className="button report-button" onClick={() => void generateReport(activeDetection)}>▤ {t.report}<span>↗</span></button> : null}</aside></div>
      </>}
    </main>
    <nav className="mobile-nav" aria-label="Mobile navigation">{navViews.slice(0, 4).map((item, index) => <button key={item} className={view === item || (item === "detections" && view === "detection") ? "active" : ""} onClick={() => setView(item)}><span>{icons[index]}</span><small>{t.nav[index]}</small></button>)}</nav>
  </div>;
}

function Kpi({ label, value, note, tone = "" }: { label: string; value: string; note: string; tone?: string }) { return <GlassCard className={`kpi-card ${tone}`}><span>{label}</span><strong>{value}</strong><small>{note}</small></GlassCard>; }
function CardHeading({ eyebrow, title, icon }: { eyebrow: string; title: string; icon: string }) { return <div className="card-heading"><div><div className="eyebrow">{eyebrow}</div><h2>{title}</h2></div><span className="heading-icon">{icon}</span></div>; }
function Metric({ label, value }: { label: string; value: string }) { return <div className="metric"><span>{label}</span><strong>{value}</strong></div>; }
function SceneCard({ t, language, scene }: { t: Copy; language: Language; scene: Scene | null }) { return <GlassCard className="scene-card"><CardHeading eyebrow={t.latestScene} title={t.satelliteAcquisition} icon="◌" /><div className="scene-title"><span className="satellite-icon">S1</span><div><strong>{scene?.satellite ?? "Sentinel-1"}</strong><small>GRD • VV + VH</small></div></div><div className="metric-list"><Metric label={t.acquired} value={formatDate(scene?.acquisition_time, language)} /><Metric label={t.orbit} value={scene?.orbit_direction ?? "—"} /><Metric label={t.resolution} value="10 m" /></div><div className="scene-id">{t.sceneId}<span>{scene?.external_scene_id?.slice(0, 26) ?? "—"}</span></div></GlassCard>; }
function DetectionCard({ t, detection, onAnalyze, onOpen }: { t: Copy; detection: Detection | null; onAnalyze: () => void; onOpen: () => void }) { return <GlassCard className="detection-card"><CardHeading eyebrow={t.aiScreening} title={t.latestDetection} icon="◉" />{detection ? <><div className="detection-head"><div><div className="big-number">{detection.area_km2.toFixed(2)} <small>km²</small></div><span className="muted">{t.estimatedArea}</span></div><StatusPill level={detection.risk_level} label={t.risk[detection.risk_level]} /></div><div className="confidence-row"><div><span className="muted">{t.meanConfidence}</span><strong>{Math.round(detection.mean_confidence * 100)}%</strong></div><div className="confidence-bar"><span style={{ width: `${detection.mean_confidence * 100}%` }} /></div></div><div className="warning-box"><span>!</span><p>{t.warning}</p></div><button className="button button-secondary full" onClick={onOpen}>{t.details}<span>→</span></button></> : <div className="empty-state"><span className="empty-icon">○</span><strong>{t.noAnalyses}</strong><p>{t.noAnalysesText}</p><button className="button button-secondary full" onClick={onAnalyze}>{t.analyzeArea}</button></div>}</GlassCard>; }
function TrendCard({ t, detections }: { t: Copy; detections: Detection[] }) { const localizedTrend = detections.slice(-8).map((item, index) => ({ name: index === detections.slice(-8).length - 1 ? t.now : `−${detections.slice(-8).length - index - 1}`, score: Math.round(item.mean_confidence * 100) })); return <GlassCard className="trend-card"><div className="trend-header"><div><div className="eyebrow">{t.trend}</div><h2>{t.screeningConfidence}</h2></div><span className="trend-badge"><small>{t.actualSequence}</small></span></div><div className="chart-wrap">{localizedTrend.length ? <ResponsiveContainer width="100%" height="100%"><AreaChart data={localizedTrend}><defs><linearGradient id="confidence" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#d8a84e" stopOpacity={.3} /><stop offset="100%" stopColor="#d8a84e" stopOpacity={0} /></linearGradient></defs><XAxis dataKey="name" axisLine={false} tickLine={false} tick={{ fill: "#8e9189", fontSize: 10 }} /><Tooltip contentStyle={{ background: "#242620", border: "1px solid #4c4d43", borderRadius: 10 }} /><Area type="monotone" dataKey="score" stroke="#d8a84e" strokeWidth={2} fill="url(#confidence)" /></AreaChart></ResponsiveContainer> : <div className="empty-state"><strong>{t.noAnalyses}</strong><p>{t.noAnalysesText}</p></div>}</div></GlassCard>; }
function AnalysisPanel({ t, language, scene, loading, running, job, drawing, selectedPoint, onDraw, onFind, onRun }: { t: Copy; language: Language; scene: Scene | null; loading: boolean; running: boolean; job: AnalysisStatus | null; drawing: boolean; selectedPoint: [number, number] | null; onDraw: () => void; onFind: () => void; onRun: () => void }) { return <GlassCard className="analysis-panel"><CardHeading eyebrow={t.workflow} title={t.workflowTitle} icon="⌁" /><p className="panel-intro">{t.workflowIntro}</p><WorkflowStep index="01" title={t.defineArea} note={selectedPoint ? t.mapReady : t.choosePoint} active action={<button className="button button-secondary small" onClick={onDraw}>{drawing ? t.clickMap : t.selectArea}</button>} /><WorkflowStep index="02" title={t.findLatest} note={scene ? `${scene.satellite} • ${formatDate(scene.acquisition_time, language)}` : t.daysBack} active={Boolean(scene)} action={<button className="button button-secondary small" onClick={() => void onFind()} disabled={loading}>{loading ? t.searching : t.findScene}</button>} /><WorkflowStep index="03" title={t.runScreening} note={job?.status === "completed" ? t.detectionReady : t.openModel} active={running || job?.status === "completed"} action={<button className="button button-primary small" onClick={() => void onRun()} disabled={running}>{running ? `${job?.progress ?? 0}%` : t.runAnalysis}</button>} />{job && job.status !== "completed" ? <div className="progress-area"><div className="progress-label"><span>{t.stages[Math.min(5, Math.floor(job.progress / 17))]}</span><strong>{job.progress}%</strong></div><div className="progress-track"><span style={{ width: `${job.progress}%` }} /></div><div className="stage-list">{t.stages.map((stage, index) => <span className={job.progress >= (index + 1) * 16 ? "done" : ""} key={stage}>● {stage}</span>)}</div></div> : null}</GlassCard>; }
function WorkflowStep({ index, title, note, active = false, action }: { index: string; title: string; note: string; active?: boolean; action: React.ReactNode }) { return <div className="workflow-row"><div className={`step-index ${active ? "active" : ""}`}>{index}</div><div><strong>{title}</strong><small>{note}</small></div>{action}</div>; }
function DetectionsPanel({ t, language, detections, onOpen }: { t: Copy; language: Language; detections: Detection[]; onOpen: (d: Detection) => void }) { return <GlassCard className="list-panel"><CardHeading eyebrow={t.register} title={t.screened} icon="◉" />{detections.length ? <div className="record-list">{[...detections].reverse().map((d) => <button className="record-row" key={d.id} onClick={() => onOpen(d)}><span><strong>{t.anomaly}</strong><small>{formatDate(d.acquisition_time, language)} • {d.coordinates[1].toFixed(3)}°N, {d.coordinates[0].toFixed(3)}°E</small></span><span className="record-metrics"><b>{d.area_km2.toFixed(2)} km²</b><StatusPill level={d.risk_level} label={t.risk[d.risk_level]} /></span></button>)}</div> : <div className="empty-state wide"><strong>{t.noDetections}</strong><p>{t.noDetectionsText}</p></div>}</GlassCard>; }
function ReportsPanel({ t, language, detections, generatedReports, onGenerate }: { t: Copy; language: Language; detections: Detection[]; generatedReports: Record<string, string>; onGenerate: (d: Detection) => void }) { return <GlassCard className="list-panel"><CardHeading eyebrow={t.reportCenter} title={t.reportTitle} icon="▤" /><p className="panel-intro">{t.reportIntro}</p>{detections.length ? <div className="record-list">{[...detections].reverse().map((d) => <div className="record-row report-row" key={d.id}><span><strong>{t.reportName} {d.id.slice(0, 8).toUpperCase()}</strong><small>{d.satellite} • {formatDate(d.acquisition_time, language)}</small></span><button className="button button-secondary small" onClick={() => onGenerate(d)}>{generatedReports[d.id] ? t.downloadAgain : t.generatePdf}</button></div>)}</div> : <div className="empty-state wide"><strong>{t.noReport}</strong><p>{t.noReportText}</p></div>}</GlassCard>; }
function DetectionDetailsPage({ detection, t, language, onBack, onReport, onReview }: { detection: Detection; t: Copy; language: Language; onBack: () => void; onReport: () => void; onReview: (action: "CONFIRM" | "FALSE_POSITIVE" | "ESCALATE") => void }) { return <motion.section initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} className="detail-page"><div className="detail-page-head"><div><button className="text-button" onClick={onBack}>← {t.back}</button><div className="eyebrow">{t.incident} / {detection.id.slice(0, 8)}</div><h2>{t.potential}</h2><p>{detection.explanation || detection.warning}</p></div><StatusPill level={detection.risk_level} label={t.risk[detection.risk_level]} /></div><div className="comparison"><figure><img src={api.assetUrl(detection.image_url)} alt={t.preview} /><figcaption>{t.preview}</figcaption></figure><figure><img src={api.assetUrl(detection.mask_url)} alt={t.mask} /><figcaption>{t.mask}</figcaption></figure></div><div className="detail-layout"><GlassCard className="detail-metrics"><CardHeading eyebrow={t.result} title={t.metrics} icon="◉" /><div className="detail-grid"><Metric label={t.estimatedArea} value={`${detection.area_km2.toFixed(2)} km²`} /><Metric label={t.meanConfidence} value={`${Math.round(detection.mean_confidence * 100)}%`} /><Metric label={t.maxConfidence} value={`${Math.round(detection.max_confidence * 100)}%`} /><Metric label={t.coordinates} value={`${detection.coordinates[1].toFixed(3)}°N / ${detection.coordinates[0].toFixed(3)}°E`} /><Metric label={t.modelVersion} value={detection.model_version} /><Metric label={t.verification} value={detection.verification_status} /></div></GlassCard><GlassCard className="method-card"><CardHeading eyebrow={t.responsible} title={t.nextAction} icon="✓" /><p>{t.nextText}</p><div className="review-actions"><button className="button button-primary" onClick={() => onReview("CONFIRM")}>{t.confirm}</button><button className="button button-secondary" onClick={() => onReview("FALSE_POSITIVE")}>{t.falsePositive}</button><button className="button button-secondary" onClick={() => onReview("ESCALATE")}>{t.escalate}</button></div><button className="button button-primary full" onClick={onReport}>{t.generatePdf}<span>↗</span></button></GlassCard></div><small className="modal-foot">{t.source}: {detection.satellite} • {formatDate(detection.acquisition_time, language)} • {t.live}</small></motion.section>; }
function AboutPage({ t, onAnalyze }: { t: Copy; onAnalyze: () => void }) { return <section className="about-page"><div className="about-hero"><div><div className="eyebrow">{t.aboutEyebrow}</div><h2>{t.aboutHero}</h2><p>{t.aboutText}</p><button className="button button-primary" onClick={onAnalyze}>{t.explore}</button></div><div className="impact-orbit"><span>VV</span><strong>AI</strong><span>VH</span></div></div><div className="about-grid"><InfoCard eyebrow={t.observe} title={t.observeTitle} body={t.observeText} /><InfoCard eyebrow={t.screen} title={t.screenTitle} body={t.screenText} /><InfoCard eyebrow={t.verify} title={t.verifyTitle} body={t.verifyText} /></div><GlassCard className="roadmap-card"><CardHeading eyebrow={t.scalability} title={t.beyond} icon="↗" /><p>{t.beyondText}</p></GlassCard></section>; }
function InfoCard({ eyebrow, title, body }: { eyebrow: string; title: string; body: string }) { return <GlassCard><div className="eyebrow">{eyebrow}</div><h3>{title}</h3><p>{body}</p></GlassCard>; }
